# Generated by Django 4.1 on 2024-12-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome do item")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="fotos_itens/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(verbose_name="Quantidade em estoque"),
                ),
            ],
        ),
    ]
