# Generated by Django 4.1 on 2024-12-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_itemestoque"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name="itemestoque",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="estoque/", verbose_name="Foto"
            ),
        ),
    ]
