# Generated by Django 4.1 on 2024-12-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_cliente_email_venda_itemvenda"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemvenda",
            old_name="item_estoque",
            new_name="produto",
        ),
        migrations.AlterField(
            model_name="venda",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
