# Generated by Django 4.1 on 2024-12-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_item_estoque_itemvenda_produto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCarrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name="venda",
            old_name="funcionario",
            new_name="usuario",
        ),
        migrations.AlterField(
            model_name="itemestoque",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="itemestoque",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="estoque/"),
        ),
        migrations.AlterField(
            model_name="itemestoque",
            name="nome",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="itemestoque",
            name="quantidade",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="itemestoque",
            name="valor",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="venda",
            name="forma_pagamento",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="ItemVenda",
        ),
        migrations.AddField(
            model_name="itemcarrinho",
            name="item_estoque",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.itemestoque"
            ),
        ),
        migrations.AddField(
            model_name="itemcarrinho",
            name="venda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="core.venda",
            ),
        ),
    ]
