# Generated by Django 4.1 on 2024-12-20 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_itemcarrinho_rename_funcionario_venda_usuario_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemcarrinho",
            old_name="subtotal",
            new_name="preco",
        ),
        migrations.RemoveField(
            model_name="itemcarrinho",
            name="item_estoque",
        ),
        migrations.AddField(
            model_name="itemcarrinho",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="itemcarrinho",
            name="quantidade",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="itemcarrinho",
            name="venda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.venda"
            ),
        ),
    ]
