# Generated by Django 4.1 on 2024-12-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_subtotal_itemcarrinho_preco_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venda",
            name="usuario",
        ),
        migrations.AlterField(
            model_name="itemestoque",
            name="descricao",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="itemestoque",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="estoque/", verbose_name="Foto"
            ),
        ),
        migrations.AlterField(
            model_name="itemestoque",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome do item"),
        ),
        migrations.AlterField(
            model_name="itemestoque",
            name="quantidade",
            field=models.PositiveIntegerField(verbose_name="Quantidade em estoque"),
        ),
        migrations.AlterField(
            model_name="itemestoque",
            name="valor",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Valor (R$)"
            ),
        ),
        migrations.DeleteModel(
            name="ItemCarrinho",
        ),
        migrations.DeleteModel(
            name="Venda",
        ),
    ]
