# Generated by Django 5.1.5 on 2025-01-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_carrinho_alter_itemestoque_descricao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrinho",
            name="comprovante_pix",
            field=models.ImageField(
                blank=True, null=True, upload_to="comprovantes_pix/"
            ),
        ),
    ]
