# Generated by Django 5.1.5 on 2025-01-16 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_carrinho_comprovante_pix"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroPonto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(auto_now_add=True)),
                ("entrada", models.TimeField(blank=True, null=True)),
                ("saida", models.TimeField(blank=True, null=True)),
                ("total_trabalhado", models.DurationField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
