# Generated by Django 5.1.5 on 2025-01-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_registroponto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RegistroPonto",
        ),
    ]
