# Generated by Django 5.1.5 on 2025-01-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_registroponto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registroponto",
            name="criado_em",
        ),
        migrations.AddField(
            model_name="registroponto",
            name="valor_em_caixa_entrada",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="registroponto",
            name="valor_em_caixa_saida",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
