# Generated by Django 5.1.5 on 2025-01-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_registroponto_criado_em_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="valor_hora",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
