# Generated by Django 5.1.5 on 2025-01-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_configuracao_remove_customuser_valor_hora"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrinho",
            name="data_venda",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="carrinho",
            name="valor_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
