# Generated by Django 5.1.5 on 2025-01-17 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_carrinho_data_venda_carrinho_valor_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aviso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
                ("aparecer_uma_vez", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AvisoVisualizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_visualizado", models.DateTimeField(auto_now_add=True)),
                (
                    "aviso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.aviso"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
