# Generated by Django 5.1.5 on 2025-01-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_aviso_avisovisualizado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aviso",
            name="aparecer_uma_vez",
        ),
    ]
