# Generated by Django 5.1.5 on 2025-01-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_remove_aviso_aparecer_uma_vez"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemestoque",
            name="foto",
            field=models.ImageField(
                default="path/to/default/image.jpg", upload_to="img/"
            ),
        ),
    ]
