# Generated by Django 5.1.5 on 2025-01-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_itemestoque_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrinho",
            name="comprovante_pix",
            field=models.ImageField(
                blank=True, null=True, upload_to="img/comprovantes_pix/"
            ),
        ),
    ]
