# Generated by Django 5.1.5 on 2025-01-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_carrinho_comprovante_pix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrinho",
            name="comprovante_pix",
            field=models.ImageField(
                blank=True, null=True, upload_to="comprovantes_pix/"
            ),
        ),
        migrations.AlterField(
            model_name="itemestoque",
            name="foto",
            field=models.ImageField(
                default="path/to/default/image.jpg", upload_to="estoque/"
            ),
        ),
    ]
