# Generated by Django 5.1.5 on 2025-01-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_carrinho_comprovante_pix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="primeiro_acesso",
            field=models.BooleanField(default=True),
        ),
    ]
