# Generated by Django 5.1.5 on 2025-01-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_email_anexo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Anexo",
        ),
        migrations.DeleteModel(
            name="Email",
        ),
    ]
