# Generated by Django 5.1.5 on 2025-01-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_horariofuncionamento_excecaohorario"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExcecaoHorario",
        ),
        migrations.DeleteModel(
            name="HorarioFuncionamento",
        ),
    ]
