# Generated by Django 5.1.5 on 2025-01-29 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_delete_excecaohorario_delete_horariofuncionamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="HorarioFuncionamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("seg", "Segunda-feira"),
                            ("ter", "Terça-feira"),
                            ("qua", "Quarta-feira"),
                            ("qui", "Quinta-feira"),
                            ("sex", "Sexta-feira"),
                            ("sab", "Sábado"),
                            ("dom", "Domingo"),
                        ],
                        max_length=3,
                    ),
                ),
                ("hora_abertura", models.TimeField()),
                ("hora_fechamento", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ExcecaoHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_excecao", models.DateField()),
                ("horario_alterado", models.BooleanField(default=False)),
                (
                    "horario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.horariofuncionamento",
                    ),
                ),
            ],
        ),
    ]
