# Generated by Django 5.1.5 on 2025-01-29 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_horariofuncionamento_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="horariofuncionamento",
            options={},
        ),
        migrations.RenameField(
            model_name="horariofuncionamento",
            old_name="horario_abertura",
            new_name="abertura",
        ),
        migrations.RenameField(
            model_name="horariofuncionamento",
            old_name="horario_fechamento",
            new_name="fechamento",
        ),
        migrations.RemoveField(
            model_name="excecaohorario",
            name="status",
        ),
        migrations.AddField(
            model_name="excecaohorario",
            name="motivo",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="excecaohorario",
            name="horario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="excecoes",
                to="core.horariofuncionamento",
            ),
        ),
        migrations.AlterField(
            model_name="horariofuncionamento",
            name="dia_semana",
            field=models.IntegerField(
                choices=[
                    (0, "Segunda-feira"),
                    (1, "Terça-feira"),
                    (2, "Quarta-feira"),
                    (3, "Quinta-feira"),
                    (4, "Sexta-feira"),
                    (5, "Sábado"),
                    (6, "Domingo"),
                ]
            ),
        ),
    ]
