# Generated by Django 5.1.5 on 2025-01-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_horariofuncionamento_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="excecaohorario",
            name="motivo",
        ),
    ]
