# Generated by Django 5.1.5 on 2025-02-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_itemestoque_prioridade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avisovisualizado",
            name="aviso",
        ),
        migrations.RemoveField(
            model_name="avisovisualizado",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="carrinho",
            name="user",
        ),
        migrations.RemoveField(
            model_name="itemcarrinho",
            name="carrinho",
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
        migrations.DeleteModel(
            name="Configuracao",
        ),
        migrations.DeleteModel(
            name="Duvida",
        ),
        migrations.RemoveField(
            model_name="excecaohorario",
            name="horario",
        ),
        migrations.RemoveField(
            model_name="itemcarrinho",
            name="item_estoque",
        ),
        migrations.RemoveField(
            model_name="registroponto",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="Aviso",
        ),
        migrations.DeleteModel(
            name="AvisoVisualizado",
        ),
        migrations.DeleteModel(
            name="Carrinho",
        ),
        migrations.DeleteModel(
            name="ExcecaoHorario",
        ),
        migrations.DeleteModel(
            name="HorarioFuncionamento",
        ),
        migrations.DeleteModel(
            name="ItemCarrinho",
        ),
        migrations.DeleteModel(
            name="ItemEstoque",
        ),
        migrations.DeleteModel(
            name="RegistroPonto",
        ),
    ]
